#KEYS AND TOKENS OBTAINED FROM TWITTER FOR DEVS.

consumer_key = "YOUR CONSUMER KEY"
consumer_secret = "YOUR CONSUMER SECRET"

access_token = "YOUR ACCESS TOKEN"
access_token_secret = "YOUR SECRET ACCESS TOKEN HERE"
